repos:
  - repo: https://github.com/Quantco/pre-commit-mirrors-black
    rev: 22.6.0
    hooks:
      - id: black-conda
  - repo: https://github.com/Quantco/pre-commit-mirrors-pyupgrade
    rev: 3.0.0
    hooks:
      - id: pyupgrade-conda
  - repo: https://github.com/Quantco/pre-commit-mirrors-mypy
    rev: "0.971"
    hooks:
      - id: mypy-conda
        args:
          - --python-version 3.8
  - repo: https://github.com/Quantco/pre-commit-mirrors-flake8
    rev: 5.0.4
    hooks:
      - id: flake8-conda
        additional_dependencies: [-c, conda-forge, flake8-docstrings=1.5.0, flake8-rst-docstrings=0.0.14]
  - repo: https://github.com/Quantco/pre-commit-mirrors-isort
    rev: 5.10.1
    hooks:
      - id: isort-conda
        additional_dependencies: [-c, conda-forge, toml=0.10.2]
