services:
  gcs:
    image: fsouza/fake-gcs-server
    container_name: fake-gcs-server
    ports:
    - 4443:4443
    command: -scheme http
  azure:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - 10000:10000
    command: azurite-blob --blobHost 0.0.0.0 --loose
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniostorage
    command: server /data
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
    - 27017:27017