name: minimalkv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - dulwich
  - mock
  - pytest
  - pytest-mock
  - pytest-xdist
  - pytest-cov
  - redis-py
  - psycopg2
  - six
  - sqlalchemy
  - boto
  - boto3
  - pymongo
  - docker-compose
  - pymysql
  - pre-commit
  - setuptools-scm
  - uritools
  - sphinx
  - adlfs
  - gcsfs
