name: CI
on: [push]

jobs:
  unittest:
    name: Unit tests - ${{ matrix.PYTHON_VERSION }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ["3.7", "3.8"]
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: minimalkv_test
          POSTGRES_PASSWORD: minimalkv_test
          POSTGRES_USER: minimalkv_test
    env:
      SIMPLEKV_CI: 1
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          python-version: ${{ matrix.PYTHON_VERSION }}
          environment-file: environment.yml
      - name: Run the unittests
        shell: bash -x -l {0}
        run: |
          pip install --no-deps .
          docker run -d --name fake-gcs-server -p 4443:4443 fsouza/fake-gcs-server:v1.21.2 -scheme http
          docker run -d --name azurite -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0 --loose
          docker run -d --name minio -p 9000:9000 -e "MINIO_ACCESS_KEY=minio" -e "MINIO_SECRET_KEY=miniostorage" minio/minio server /data
          pytest -nauto
